### PR TITLE
Update Dockerfile: installs glfw3 and glew

### PR DESCRIPTION
**Pull request by satyajitghana**
Added install for missing libraries, which prevented Viewer from being built

### CODE REVIEW

**Comment by cdcseacave** [comment]
the two libraries were omitted in purpose so that the Viewer is not built, not sure how you can use the Viewer inside Docker; can you give an example?

**Comment by satyajitghana** [comment]
I've made this script which i generally use if i want to work with display apps

```
#!/bin/bash

set -e

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DOCKER_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
REPO_ROOT="$( cd -P "$( dirname "$DOCKER_DIR" )" && pwd )"

DOCKER_VERSION=$(docker version -f "{{.Server.Version}}")
DOCKER_MAJOR=$(echo "$DOCKER_VERSION"| cut -d'.' -f 1)

# no need to do `xhost +` anymore
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
touch $XAUTH
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

# specify the image, very important
IMAGE="openmvs-ubuntu:latest"
RUNTIME=$runtime

docker run ${RUNTIME} --privileged -it --rm \
	  -e NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics \
            --volume=${REPO_ROOT}/:/opt/src/ \
            --volume=$XSOCK:$XSOCK:rw \
            --volume=$XAUTH:$XAUTH:rw \
            --volume=/dev:/dev:rw \
	   --device /dev/dri \
            --net=host \
	   --ipc=host \
            --shm-size=1gb \
            --env="XAUTHORITY=${XAUTH}" \
            --env="DISPLAY=unix$DISPLAY" \
	   --entrypoint /bin/bash \
            ${IMAGE}
```

although the extra stuff like nvidia capabilities is not required, nor is the shm, ipc or network. XSOCK and XAUTH are required for passing the display.


tested works

image

**Comment by cdcseacave** [comment]
This is cool. Can you add this script as well? And point to develop.

**Comment by satyajitghana** [comment]
updated new pr https://github.com/cdcseacave/openMVS/pull/954

**Pull request closed without merging**
