### PR TITLE
Add gclowdensity option

### LINKED ISSUE #79: TextureMesh: "error: empty initial mesh" when running tutorial files w/o prior running DensifyPointCloud scene.mvs
### Specifications like the version of the project, operating system, and hardware
latest openMVG from develop branch
latest openMVS

Ubuntu 15.10 64-bit
Memory 3,8 GiB
Processor Intel® Core™ i3-4160 CPU @ 3.60GHz × 4
Graphics Intel® Haswell 
### Steps to reproduce the problem

Run Tutorial FIles (Describer Preset: Normal, Global SfM. Running w/o prior running DensifyPointCloud results in "error: empty initial mesh". If running DensifyPointCLoud prior, it works alright. Same applies if trying to run Refine Mesh. Don't know if Wiki is outdated and this is intended behaviour, so I'm reporting anyway.

Files: https://mega.nz/#F!6IUiSSwT!xb4Ie7GCjPGWqidb1lem8A

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Scene saved to OpenMVS interface format:
	11 images (11 calibrated)
	2926 Landmarks
14:38:46 [App     ] Build date: Apr 14 2016, 09:38:27
14:38:47 [App     ] CPU: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
14:38:47 [App     ] RAM: 3.77GB Physical Memory 3.91GB Virtual Memory
14:38:47 [App     ] OS: Linux 4.2.0-16-generic (x86_64)
14:38:47 [App     ] SSE & AVX compatible CPU & OS detected
14:38:47 [App     ] Command line: /home/martin-uwh/openMVG_build/software/SfM/ImageDataset_SceauxCastle/images_out/MVS_out/scene.mvs
14:38:47 [App     ] Camera model loaded: platform 0; camera  0; f 1.054x1.054; poses 11
14:38:47 [App     ] Image loaded   0: 100_7100.JPG
14:38:47 [App     ] Image loaded   1: 100_7101.JPG
14:38:47 [App     ] Image loaded   2: 100_7102.JPG
14:38:47 [App     ] Image loaded   3: 100_7103.JPG
14:38:47 [App     ] Image loaded   4: 100_7104.JPG
14:38:47 [App     ] Image loaded   5: 100_7105.JPG
14:38:47 [App     ] Image loaded   6: 100_7106.JPG
14:38:47 [App     ] Image loaded   7: 100_7107.JPG
14:38:47 [App     ] Image loaded   8: 100_7108.JPG
14:38:47 [App     ] Image loaded   9: 100_7109.JPG
14:38:47 [App     ] Image loaded  10: 100_7110.JPG
14:38:47 [App     ] Scene loaded from interface format (402ms):
	11 images (11 calibrated) with a total of 63.22 MPixels (5.75 MPixels/image)
	2926 points, 0 vertices, 0 faces
14:38:47 [App     ] Delaunay tetrahedralization completed: 2926 points -> 2728 vertices, 16668 (+114) cells, 33393 (+171) faces (63ms)
14:38:47 [App     ] Delaunay tetrahedras weighting completed: 16782 cells, 33564 faces (113ms)
14:38:47 [App     ] Delaunay tetrahedras graph-cut completed (1722.6 flow): 798 vertices, 1570 faces (26ms)
14:38:47 [App     ] Mesh reconstruction completed: 801 vertices, 1570 faces (301ms)
14:38:47 [App     ] Cleaned mesh: 0 vertices, 0 faces (3ms)
14:38:48 [App     ] Scene saved (2ms):
	11 images (11 calibrated)
	0 points, 0 vertices, 0 faces
14:38:48 [App     ] MEMORYINFO: {
14:38:48 [App     ] 	VmPeak:	  889304 kB
14:38:48 [App     ] 	VmSize:	  691612 kB
14:38:48 [App     ] } ENDINFO

14:38:48 [App     ] Build date: Apr 14 2016, 09:38:27
14:38:48 [App     ] CPU: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
14:38:48 [App     ] RAM: 3.77GB Physical Memory 3.91GB Virtual Memory
14:38:48 [App     ] OS: Linux 4.2.0-16-generic (x86_64)
14:38:48 [App     ] SSE & AVX compatible CPU & OS detected
14:38:48 [App     ] Command line: /home/martin-uwh/openMVG_build/software/SfM/ImageDataset_SceauxCastle/images_out/MVS_out/scene_mesh.mvs
14:38:48 [App     ] Scene loaded (0ms):
	11 images (11 calibrated) with a total of 63.22 MPixels (5.75 MPixels/image)
	0 points, 0 vertices, 0 faces
14:38:48 [App     ] error: empty initial mesh

### PR DESCRIPTION
**Pull request by mad-de**
Adds new option to ReconstructMesh which restores old ReconstructMesh behaviour, set to false by default. Closes #79

### CODE REVIEW

**Comment by mad-de** [comment]
@cdcseacave  I'm unsure about this change https://github.com/cdcseacave/openMVS/pull/80/commits/e151870d7ea0b12318abbfd13e939a7264c23ada which was introduced in https://github.com/cdcseacave/openMVS/commit/0100c7f99ec7b59db2e36f86f4b164bf87523407 . 
I don't get different results comparing e151870 and 81255ad so I left it aside.
Do you think it makes sense to add the "*kb" when running in gclowdensity mode?

**Comment by cdcseacave** [comment]
this is the paper explaining the mesh reconstruction: http://www.hindawi.com/journals/isrn/2014/798595/
all formulas are implemented as in the paper

**Comment by mad-de** [comment]
@cdcseacave thank you very much for providing me with the link to this paper. Quite a bit to chew on for me I'm afraid.

In the paper they state, that Sigma is "a constant that equals 2.0 times median of all edges lengths of all tetrahedra. The value represents the smallest reconstructible object."
`sigma(distsSq.GetMedian()*2)`
The way I understand it, you changed Sigma in https://github.com/cdcseacave/openMVS/commit/0100c7f99ec7b59db2e36f86f4b164bf87523407 to (squareroot (median of all  edges lengths of all tetraheda * 2))
`sigma(SQRT(distsSq.GetMedian())*2)`

So all my PR would do is to reinstate the original function, if I'm not wrong, which might well be.

As for the kb - I only found it in libs/MVS/scene.h where it is declared as [float kb=4.f]. As it doesn't seem to be in use anywhere else and if you don't want to use it anymore, maybe you can remove it from libs/MVS/Scene.h and libs/MVS/SceneReconstruct.cpp. I was unsuccesful in tracking down it's original formula in the paper.

**Comment by cdcseacave** [comment]
@mad-de please check the formula for computing the length: https://en.wikipedia.org/wiki/Norm_(mathematics)#Euclidean_norm

**Comment by mad-de** [comment]
I see - but I'm no mathematician, unfortunately, so sorry for wasting your time here, as you are probably shaking your head right now. Please feel free to correct me if I'm wrong.

`FloatArr distsSq(0, delaunay.number_of_edges());
for (delaunay_t::Finite_edges_iterator ei=delaunay.finite_edges_begin(), eei=delaunay.finite_edges_end(); ei!=eei; ++ei) {
const cell_handle_t& c(ei->first);
distsSq.Insert(normSq(CGAL2MVS<float>(c->vertex(ei->second)->point()) - CGAL2MVS<float>(c->vertex(ei->third)->point())));
}
const float sigma(SQRT(distsSq.GetMedian())*2);
const float inv2SigmaSq(0.5f/(sigma*sigma));
distsSq.Release();`

With distsSq as far as I understood, you are calculating the vectordistance from points in the tetraeders.  If you are using the euclidian norm - wouldn't you have to multiply these vectors with themselves first before squarerooting them?

Anyway - I had a couple of projects that worked before just fine and are not working anymore and I narrowed (and tested) the problem down to the squareroot you added in this commit.

**Comment by cdcseacave** [comment]
could you please send me one of those datasets that do not work anymore for debugging? (the code as is is correct, trust me)

**Comment by mad-de** [comment]
Here are the files: https://mega.nz/#F!bFcVGL7J!l6b4Op7nqEqmjf7pdw67NA

There are two folders: 
the os_coxae_50perc is one of the projects I'm working on right now. It is made with standard settings of the latest openMVG. I also attached the standard tutorial files.
You can find the options that were used in the Pipeline_Options.txt in the matches and reconstruct folder.
I used my branch (latest openMVS with my gclowdensity option) and used it on the reconstruct folder in 4 settings:
MVS_out = openMVS without the gclowdensity setting. RefineMesh + DensifyPointcloud
MVS_out_gyclowdensity = openMVS with gclowdensity setting. RefineMesh + DensifyPointcloud
MVS_out_wo_densfiy_gclowdensity = openMVS with gclowdensity setting. RefineMesh. NO DensifyPointcloud
MVS_out_wo_densfiy = openMVS without the gclowdensity setting. RefineMesh. NO DensifyPointcloud

**Comment by mad-de** [comment]
with DensifyPointcloud, without gclowdensity (current openMVS master)
screenshot from 2016-04-18 22-10-17
with DensifyPointcloud, with gclowdensity (option from my PR activated)
screenshot from 2016-04-18 22-10-53
without DensifyPointcloud, without gclowdensity (current openMVS master)
screenshot from 2016-04-18 22-13-41
without DensifyPointcloud, with gclowdensity (option from my PR activated)
screenshot from 2016-04-18 22-14-27

**Comment by cdcseacave** [comment]
I see the problem! I will check what can be done and get back to you.

**Comment by cdcseacave** [comment]
Hi @mad-de! I can not reproduce the OpenMVG (obviously you are not using the latest version, since the latest version exports the scene in BIN format) nor the OpenMVS results, but I get the idea. Actually, it is a well know problem that manifests for very thin surfaces. Therefore, I have added a new parameter in ReconstructMesh to control the minimum thickness of the surface. The default value should be general enough, but you can adjust it if you notice this kind of behavior (holes in the mesh in thin areas).

**Comment by mad-de** [comment]
@cdcseacave they were indeed made with the latest develop openMVG version. Please check for the sfm_data.bin in the reconstruct folders. I am also using the fork for the PR of openMVS, which is based on the latest openMVS version.
The problem is not only the holes in the surface, but the "destuction" of the image when using lower density point clouds. (See my attached image 3 and the according file I attached). You can see in the attached dense model, that there is also an added "bridge", which doesn't exist in my gclowdensity setting run (correctly).
I'll try out your minimum thickness to test for the hole problems. But I think it's best to stop bothering you with my issues here and just keep using my gclowdensity fork in future..

Thanks for looking into that and for providing this great project.

**Comment by cdcseacave** [comment]
can you please confirm that the new option does or does not work for you?

**Comment by mad-de** [comment]
Hi @cdcseacave 
no option delivered good results in both cases (without densify pointcloud + with densify pointcloud). Setting the quality factor to 0.5 resulted in comparably good results like the gclowdensity options with a higher amount of vertices when using Densify Pointcloud before. Results weren't as good without. 
Do you want to see pictures / output folders?
Best wishes.

**Pull request closed without merging**
