### PR TITLE
FilterViews

### PR DESCRIPTION
**Pull request by rjanvier**

### CODE REVIEW

**Comment by ORNis** [comment]
OpenMVS/openMVS#6
#21

**Comment by cdcseacave** [comment]
Looking good, but i think you need to filter all points too, and remove the
views   that u disabled (and remove the entire point if no more views
available).

**Comment by ORNis** [comment]
Ok thanks a lot,
I will look at this at the end of the week.

**Comment by rjanvier** [comment]
I close this old one for now.

**Pull request closed without merging**
