### PR TITLE
common: improve MvsScalablePipeline.py to support existing modules and resuming

### PR DESCRIPTION
**Pull request by 4CJ7T**
- Fixed typos
- Stripped suffix from scene input then append back after valid name check to grab the wanted scene file
- Removed the use of multiple modules separated by comma
- Replaced the incremental counter and exit on first error with a check for sub scene files ending with the stripped suffix
- Added resume feature by checking if the scene has already been processed with the module suffix

### CODE REVIEW

**Review by cdcseacave — APPROVED** [review]
thx

**Comment by cdcseacave** [comment]
feel free to merge when ready

**Comment by 4CJ7T** [comment]
Sorry, I don't see a merge button.

**Comment by 4CJ7T** [comment]
ready.

**Review by cdcseacave — APPROVED** [review]

**Pull request merged**
